### ISSUE TITLE
MiniBook X support

### ISSUE THREAD

**Issue by petitstrawberry** [petitstrawberry/minibook-support#3]
一旦N100版対応を目指す

手伝ってもらっているのを書き残しておく

調べたいこと

- キーボードデバイスのパス
  - `/dev/input/by-path/platform-i8042-serio-0-event-kbd`
- トラックパッド・マウスデバイスのパス
  - `/dev/input/by-path/pci-0000:00:15.3-platform-i2c_designware.3-event-mouse`
- 画面とキーボードにそれぞれ搭載されている加速度センサの軸方向
- 機種の判定方法
  - 同じプロジェクトとしてまとめたいので機種の判別が必要
  - `/sys/devices/virtual/dmi/id/product_name`で判別できそう？
    - CPUのバージョン違いでデバイスが色々変更があればCPUごとにも細かい場合分けが必要だが...

## 参考

- [dmidecode](https://linux-hardware.org/?probe=6249e8f644&log=dmidecode)
- https://github.com/lschans/chuwi-tablet/tree/main

**Comment by petitstrawberry** [comment]
## キーボードデバイスのパス

```/dev/input/by-path/platform-i8042-serio-0-event-kbd```
MiniBook (8-inch)と同じ

**Comment by petitstrawberry** [comment]
feature/#3-minibook-xで作業する

**Comment by petitstrawberry** [comment]
機種の判別

`/sys/devices/virtual/dmi/id/product_name`

- MiniBook (8-inch)
  - MiniBook
- MiniBook X (10-inch)
  - MiniBook X ?? ネットに落ちてるdmidecodeの出力的にはたぶんそう

**Comment by petitstrawberry** [comment]
5f771c674af9f8094b923718aa48a3dfc366ebb3 で暫定的に機種の種別と, MiniBook Xの加速度センサの有効化処理を追加

**Comment by 8796n** [comment]
sudo evtest /dev/input/by-path/pci-0000:00:15.3-platform-i2c_designware.3-event-mouse
以下が結果です
[evtestlog.txt](https://github.com/user-attachments/files/16706913/evtestlog.txt)

**Comment by petitstrawberry** [comment]
235407b700e8b6ca83515ed149c5b58877c65a68 で恐らくMiniBook Xのキーボード, トラックパッド, 加速度センサを正しく扱えるようになったはずです. (trackpointerdがmousedに改名された)

```
sudo ./moused/bin/moused -d
sudo ./keyboardd/bin/keyboardd -d
sudo ./tabletmoded/bin/tabletmoded -d
```

これらが全てがうまく動いていると

```
make clean
make
sudo make install
```

でインストールされ, 画面を360°回転で自動でタブレットモードが有効化されるはずです

**Comment by 8796n** [comment]
とりいそぎ確認したところ問題なくキーボードとタッチパッドが無効になりました。
Ubuntu GNOMEにおける正しいタブレットモードがどんなもんなのか理解してないのでもう少し確認してみます。

**Comment by petitstrawberry** [comment]
報告ありがとうございます！
おそらくこちらの想定通りの動きをしているようで安心しました！色々とご協力ありがとうございました。

GNOMEはあまりタブレットモードのサポートが進んでおらずオンスクリーンが有効になるくらいで、ソフトウェアとしてはほとんど何もないです... 

ちなみにKDE Plasmaなんかだと、タブレットモード時はタッチしやすいようにUIが変化します

**Comment by petitstrawberry** [comment]
トラックパッドが問答無用で無効化されている。

パススルー設定が抜けるのか、初期化が間違っているのか。おそらく後者

**Comment by 8796n** [comment]
sudo ./moused/bin/moused -d
[moused.log](https://github.com/user-attachments/files/16710017/moused.log)

sudo evtest > ~/evtestlog16.txt
で16を選んだときのログです
[evtestlog16.txt](https://github.com/user-attachments/files/16710018/evtestlog16.txt)

**Comment by petitstrawberry** [comment]
原因がなんなくわかりました。やはり初期化が間違っているようです。なんとかします

**Comment by 8796n** [comment]
sudo journalctl -b | grep event16
エラー出てました
 8月 22 20:18:35 MiniBook-X gnome-shell[2201]: libinput error: event16 - MiniBookSupport Virtual Mouse: kernel bug: device has min == max on ABS_X

**Comment by petitstrawberry** [comment]
結構盛大にやらかしてる感じですね、ありがとうございます。

**Comment by petitstrawberry** [comment]
おそらく修正できた

**Comment by 8796n** [comment]
タッチパッドのオンオフに関しては想定している挙動になってると思います。
対応ありがとうございました！

**Comment by petitstrawberry** [comment]
細かい挙動に問題はまだあるが、機種特有の対応は終了したので閉めます。ご協力ありがとうございました。
